class error_code:
    ERROR_CONFIGURATION_NOT_FOUND   = 0x8001;
    ERROR_SCRIPT_NOT_FOUND          = 0x8002;
    ERROR_SCRIPT_UNKNOWN_COMMAND    = 0x8003;
    ERROR_SCRIPT_INCORRECT_FORMAT   = 0x8004;
    ERROR_HTTP_SERVER_RUNTIME       = 0x8005;